version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/db/database.db
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: sh -c "node src/lib/init-database.js && npm start"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    restart: unless-stopped