version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./database.db:/app/database.db
      - ./public/avatars:/app/public/avatars
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint:
      - sh
      - -c
      - |
        # 检查并创建数据库目录（如果不存在）
        mkdir -p /app
        
        # 检查构建产物是否存在
        if [ ! -d "/app/.next" ]; then
          echo "错误：构建产物缺失！请确保Docker构建过程正确完成"
          exit 1
        fi
        
        # 确保数据库文件存在且具有正确权限（使用root权限执行）
        if [ ! -f "/app/database.db" ]; then
          echo "数据库文件不存在，创建空数据库文件..."
          # 使用临时文件避免权限问题
          echo "" > /tmp/empty.db
          cp /tmp/empty.db /app/database.db
          # 尝试设置权限，但不依赖于chmod成功
          chmod 666 /app/database.db || echo "警告：无法设置数据库文件权限"
          echo "空数据库文件创建完成"
        else
          echo "设置数据库文件权限..."
          chmod 666 /app/database.db || echo "警告：无法设置数据库文件权限"
        fi
        
        # 确保构建产物目录权限正确
        chmod -R 755 /app/.next || echo "警告：无法设置构建产物权限"
        
        # 直接启动应用
        echo "启动应用..."
        npm start

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public/avatars:/usr/share/nginx/html/avatars:ro
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3